apiVersion: v1
kind: ConfigMap
metadata:
  name: kk-payments-config
data:
  DB_HOST: "kk-payments-db.kijani-staging.svc.cluster.local"
  ENVIRONMENT: "staging"
  RECEIPTS_BUCKET: "kk-payments-receipts-staging"
  LOG_LEVEL: "debug"
